spring.application.name: communication-scheduler-service

#server configuration
server:
  port: ${APP_PORT:8084}
  tomcat:
    threads:
      max: ${SPRING_TOMCAT_THREADS:250}

#database configuration
spring:
  datasource:
    url: jdbc:mysql://${APP_DB_HOST:localhost}:${APP_DB_PORT:3307}/communication_scheduler_service
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration

#configuration to export metrics to prometheus
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

#scheduler configuration
scheduler:
  startTaskScheduler: ${APP_START_TASK_SCHEDULER:true} # flag to start normal scheduler.
  noOfTaskSchedulerThreads: ${APP_NO_OF_TASK_SCHEDULER_THREADS:1} # number of normal scheduler threads.
  noOfTaskSchedulerRunnableThreads: ${APP_NO_OF_TASK_SCHEDULER__RUNNABLE_THREADS:10} # number of normal scheduler runnable threads.
  noOfJobsToProcess: ${APP_NO_OF_JOBS_TO_PROCESS:5} # number of normal jobs to process in single run.
  noOfJobsExecutorThreads: ${APP_NO_OF_JOBS_EXECUTOR_THREADS:10} # number of normal scheduler executor threads.
  startFailedTaskScheduler: ${APP_START_FAILED_TASK_SCHEDULER:false} # flag to start failed scheduler.
  noOfFailedTaskSchedulerThreads: ${APP_NO_OF_FAILED_TASK_SCHEDULER_THREADS:1} # number of failed scheduler threads.
  noOfFailedTaskSchedulerRunnableThreads: ${APP_NO_OF_FAILED_TASK_SCHEDULER_RUNNABLE_THREADS:10} # number of failed scheduler runnable threads.
  noOfFailedJobsToProcess: ${APP_NO_OF_FAILED_JOBS_TO_PROCESS:5} # number of failed jobs to process in single run.
  noOfFailedJobsExecutorThreads: ${APP_NO_OF_FAILED_JOBS_EXECUTOR_THREADS:10} # number of failed scheduler executor threads.
  failedJobRetryCount: ${APP_FAILED_JOB_RETRY_COUNT:5} # maximum number retry count for failed jobs.

#email provider config
senderProviderConfiguration:
  simulate:
    host: http://127.0.0.1
    port: 8081
    url: /send/communication
  mailgun:
    host: https://api.mailgun.net
    url: /v3/${APP_MAILGUN_SENDING_DOMAIN}/messages
    apiKey: ${APP_MAILGUN_API_KEY}
    sendingDomain: ${APP_MAILGUN_SENDING_DOMAIN}


sender:
  provider: ${APP_SENDER_PROVIDER:MAILGUN}
  from: "Scheduled Reminder"
  subject: "Your Scheduled Email Reminder"



