spring.application.name: communication-scheduler-service

server:
  port: ${APP_PORT:8084}
  tomcat:
    threads:
      max: ${SPRING_TOMCAT_THREADS:250}

spring:
  datasource:
    url: jdbc:mysql://${APP_DB_HOST:localhost}:${APP_DB_PORT:3307}/communication_scheduler_service
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

scheduler:
  startTaskScheduler: ${APP_START_TASK_SCHEDULER:true}
  noOfTaskSchedulerThreads: ${APP_NO_OF_TASK_SCHEDULER_THREADS:1}
  noOfTaskSchedulerRunnableThreads: ${APP_NO_OF_TASK_SCHEDULER__RUNNABLE_THREADS:10}
  noOfJobsToProcess: ${APP_NO_OF_JOBS_TO_PROCESS:5}
  noOfJobsExecutorThreads: ${APP_NO_OF_JOBS_EXECUTOR_THREADS:10}
  startFailedTaskScheduler: ${APP_START_FAILED_TASK_SCHEDULER:false}
  noOfFailedTaskSchedulerThreads: ${APP_NO_OF_FAILED_TASK_SCHEDULER_THREADS:1}
  noOfFailedTaskSchedulerRunnableThreads: ${APP_NO_OF_FAILED_TASK_SCHEDULER_RUNNABLE_THREADS:10}
  noOfFailedJobsToProcess: ${APP_NO_OF_FAILED_JOBS_TO_PROCESS:5}
  noOfFailedJobsExecutorThreads: ${APP_NO_OF_FAILED_JOBS_EXECUTOR_THREADS:10}
  failedJobRetryCount: ${APP_FAILED_JOB_RETRY_COUNT:5}

senderProviderConfiguration:
  simulate:
    host: http://127.0.0.1
    port: 8081
    url: /send/communication

senderProvider: SIMULATE

